# Generated by Django 4.0.2 on 2022-02-15 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_user_fullname_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='User_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
