# Generated by Django 4.0.2 on 2022-02-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
