# Generated by Django 4.0.2 on 2022-02-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_appointments_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='User_id',
            new_name='User_Id',
        ),
    ]
