# Generated by Django 4.0.2 on 2022-02-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_user_id_appointments_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='Email',
            field=models.CharField(default=111, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='First_Name',
            field=models.CharField(default=111, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='Last_Name',
            field=models.CharField(default=111, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='Phone',
            field=models.CharField(default=111, max_length=30),
            preserve_default=False,
        ),
    ]
