# Generated by Django 4.0.2 on 2022-02-16 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespictures',
            name='alt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicespictures',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesvideos',
            name='alt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicesvideos',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
