# Generated by Django 4.0.2 on 2022-02-18 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicespictures_alt_servicespictures_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='servicespictures',
            options={'verbose_name': 'Services Picture', 'verbose_name_plural': 'Services Pictures'},
        ),
        migrations.AlterModelOptions(
            name='servicesvideos',
            options={'verbose_name': 'Services Video', 'verbose_name_plural': 'Services Videos'},
        ),
        migrations.AddField(
            model_name='packages',
            name='pck_name',
            field=models.CharField(default='Package', max_length=250),
        ),
        migrations.AddField(
            model_name='packages',
            name='pck_price',
            field=models.IntegerField(default=800),
        ),
        migrations.AddField(
            model_name='packages',
            name='sv_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.services'),
        ),
        migrations.AlterField(
            model_name='servicespictures',
            name='alt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicespictures',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
