# Generated by Django 4.0.2 on 2022-02-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_packages_pck_price_alter_packages_sv_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packages',
            options={'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
    ]
