# Generated by Django 4.0.2 on 2022-02-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_packages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=11),
        ),
    ]
